#!/bin/sh
#⭐️#
echo "----------------------------------------------------------------------"
echo "请更新系统密码"
echo "Please update the system password"
echo "----------------------------------------------------------------------"
sleep 2
# 提示用户输入新密码
read -s -p "Enter new password: " new_password
echo

# 提示用户再次输入新密码进行确认
read -s -p "Confirm new password: " confirm_password
echo

# 检查两次输入的密码是否一致
if [ "$new_password" != "$confirm_password" ]; then
  echo "Passwords do not match. Please try again."
  exit 1
fi

# 根据不同的发行版选择对应的命令更新密码
if [ -x "$(command -v passwd)" ]; then
  # Ubuntu
  echo "root:$new_password" | passwd --stdin root
else
  # CentOS
  echo "root:$new_password" | chpasswd
fi

# 检查密码更新是否成功
if [ $? -eq 0 ]; then
  echo "Password updated successfully."
  echo "密码更新成功."
else
  echo "Failed to update password."
  echo "更新密码失败."
fi
