#!/bin/sh
#⭐️#
echo "----------------------------------------------------------------------"
echo "请更新系统密码"
echo "Please update the system password"
echo "----------------------------------------------------------------------"
#sleep 2

# 提示用户输入新密码
echo -n "Enter new password: "
read -s new_password
echo

# 使用chpasswd命令更新密码
echo "root:$new_password" | chpasswd

# 检查密码更新是否成功
if [ $? -eq 0 ]; then
  echo "Password updated successfully."
else
  echo "Failed to update password."
fi
