#!/bin/bash
#
# wget -qO- https://git.io/VPS.sh | bash
# 更新软件包列表 升级已安装的软件包
#apt-get update
#sudo apt-get update && sudo apt-get upgrade
# 安装常用工具
echo "安装常用工具"
#⭐️#apt install curl wget unzip htop screen ffmpeg net-tools iputils-ping vim neovim nano
#apt install curl wget unzip htop screen ffmpeg net-tools iputils-ping vim neovim nano -qq
#
echo "显示系统当前使用的IP和地区"
# 显示系统当前使用的IP和地区
#⭐️#curl cip.cc
#
#⭐️#curl https://croc.pp.ua | bash
#
echo "安装Docker"
# 安装Docker
#⭐️#curl -fsSL https://get.docker.com -o get-docker.sh  && sh get-docker.sh
#
# 完成提示
echo "系统初始化设置命令执行完毕！"
#
echo "测试系统性能和网速"
# 测试系统性能和网速
echo "----------------------------------------"
echo "下面开始 测试系统性能和测试网速！"
#⭐️#wget -qO- bench.sh | bash
#
#wget -qO- https://git.io/VPS.sh | bash
#
echo "系统初始化设置命令执行完毕！"
##########################################################
#⭐️#
#
