#!/bin/bash
# 之前被Windows编辑符号^M搞死！！！
# wget -qO- https://git.io/VPS.sh | bash
#⭐️#
echo -e "2\n1024" | bash <(wget -qO- gg.gg/addswap 2> /dev/null)
echo -e "1\n1024" | bash <(wget -qO- gg.gg/addswap 2> /dev/null)
echo "----------------------------------------------------------------------"
echo "请更新系统密码"
sleep 2
echo "----------------------------------------------------------------------"
#wget -qO- https://raw.githubusercontent.com/wrtpi/update/main/passwdupdate | bash
wget -qO passwall.sh gg.gg/passwall
chmod +x passwall.sh
#./passwall.sh
# 提示用户输入新密码
#⭐️#echo "Enter new password:"
# 通过交互式环境调用stty命令
#⭐️#stty -echo
# 读取用户输入的新密码
#⭐️#read new_password
# 启用输入回显
#⭐️#stty echo
#
# 提示用户输入验证密码
#⭐️#echo "Confirm new password:"
# 通过交互式环境调用stty命令
#⭐️#stty -echo
# 读取用户输入的验证密码
#⭐️#read confirm_password
# 启用输入回显
#⭐️#stty echo
# 执行脚本，并将读取的密码作为参数传递
./passwall.sh </dev/tty  "$new_password" "$confirm_password"
rm -rf passwall.sh
#⭐️#
echo "----------------------------------------------------------------------"
echo "稍等2秒后继续执行程序 ------>------>------>------>------>------>------>"
sleep 2
echo "Set up IPV6 DNS resolution IPv4 DomainName"
sleep 2
##mv /etc/resolv.conf /etc/resolv.conf.bak && echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6" > /etc/resolv.conf
mv /etc/resolv.conf /etc/resolv.conf.bak && echo -e "nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6\nnameserver 8.8.8.8\nnameserver 1.1.1.1" > /etc/resolv.conf
#⭐️#
echo "----------------------------------------------------------------------"
echo "更新软件包列表 升级已安装的软件包"
sleep 2
apt-get update
#sudo apt-get update && sudo apt-get upgrade -y
echo "----------------------------------------------------------------------"
sleep 2
echo "安装常用工具"
apt install curl wget unzip htop screen ffmpeg net-tools iputils-ping bash-completion vim neovim nano neofetch jq -y
#⭐️#apt install curl wget unzip htop screen ffmpeg net-tools iputils-ping bash-completion vim neovim nano neofetch jq
#apt install curl wget unzip htop screen ffmpeg net-tools iputils-ping bash-completion vim neovim nano neofetch jq -qq
echo "----------------------------------------------------------------------"
#⭐️#
echo "安装命令工具"
curl https://croc.889.pp.ua | bash
echo "----------------------------------------------------------------------"
#⭐️#
echo "添加配置到 ~/.bashrc 文件末尾"
echo 'if [ -f /usr/share/bash-completion/bash_completion ]; then' >> ~/.bashrc
echo '    . /usr/share/bash-completion/bash_completion' >> ~/.bashrc
echo 'fi' >> ~/.bashrc
echo "重新加载 ~/.bashrc 文件"
source ~/.bashrc
#⭐️#
echo "设置时区为亚洲/上海"
timedatectl set-timezone Asia/Shanghai
#⭐️# 显示系统当前查看时间和时区
timedatectl
echo "----------------------------------------------------------------------"
echo "一键设置Linux终端支持中文显示"
sleep 2
wget -N --no-check-certificate https://raw.githubusercontent.com/wrtpi/zh_CN/master/zh_CN.sh && bash zh_CN.sh
echo "----------------------------------------------------------------------"
echo "显示系统当前使用的IP和地区"
#⭐️# 显示系统当前使用的IP和地区
curl cip.cc
echo "----------------------------------------------------------------------"
sleep 2
#⭐️#
echo "安装开源的Docker容器化相关组件"
sleep 2
curl -fsSL https://get.docker.com -o get-docker.sh  && sh get-docker.sh
#
echo "----------------------------------------------------------------------"
echo "系统即将完成初始化设置！"
echo "----------------------------------------------------------------------"
#⭐️#
#echo "给系统增加SWAP虚拟分区文件，文件大小可以自己输入，默认可以是1024MB！"
#sleep 2
#echo -e '1\n1024' | bash \<(curl -s -L https://raw.githubusercontent.com/wrtpi/addswap/main/addswap.sh)
#echo -e "1\n1024" | bash <(curl -s -L https://raw.githubusercontent.com/wrtpi/addswap/main/addswap.sh)
#curl -s -L https://raw.githubusercontent.com/wrtpi/addswap/main/addswap.sh > /tmp/addswap.sh
#curl -s -L https://raw.githubusercontent.com/wrtpi/addswap/main/addswap.sh > addswap.sh
#⭐️#wget -O addswap.sh https://raw.githubusercontent.com/wrtpi/addswap/main/addswap.sh
#⭐️#echo -e "1\n1024" > params
#⭐️#env PARAMS_FILE=params bash addswap.sh
#⭐️#rm addswap.sh params
#⭐️#
echo "----------------------------------------------------------------------"
echo "系统初始化设置命令执行完毕！"
echo "----------------------------------------------------------------------"
#⭐️#
echo "----------------------------------------------------------------------"
echo "显示系统相关信息，系统名称、内核版本、主机名、CPU型号、内存、GPU等！"
echo "----------------------------------------------------------------------"
neofetch
echo "----------------------------------------------------------------------"
#⭐️#
echo "----------------------------------------------------------------------"
echo "下面开始 测试系统性能和测试网速！"
echo "----------------------------------------------------------------------"
#⭐️#
sleep 6
wget -qO- bench.sh | bash
#
#wget -qO- https://git.io/VPS.sh | bash
echo "----------------------------------------------------------------------"
echo "系统初始化设置命令执行完毕！"
echo "----------------------------------------------------------------------"
##########################################################
#⭐️#
